name: API Proxy
on:
  api:
    types: [chat]

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
      - name: Proxy Request
        with:
          script: |
            const response = await fetch('https://www.blackbox.ai/api/chat', {
              method: 'POST',
              headers: {
                'Authorization': process.env.BB_API_KEY,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(context.payload)
            });
            const data = await response.json();
            return data;
